module Pokemon.Move.Effect.Names
  ( EffectName(..)
  ) where
data EffectName =
    AccuracyDown1Effect
  | AttackDown1Effect
  | AttackDownSideEffect
  | AttackTwiceEffect
  | AttackUp1Effect
  | AttackUp2Effect
  | BideEffect
  | BurnSideEffect1
  | BurnSideEffect2
  | ChargeEffect
  | ConfusionEffect
  | ConfusionSideEffect
  | ConversionEffect
  | DefenseDown1Effect
  | DefenseDown2Effect
  | DefenseDownSideEffect
  | DefenseUp1Effect
  | DefenseUp2Effect
  | DisableEffect
  | DrainHpEffect
  | DreamEaterEffect
  | EvasionUp1Effect
  | ExplodeEffect
  | FlinchSideEffect1
  | FlinchSideEffect2
  | FlyEffect
  | FocusEnergyEffect
  | FreezeSideEffect
  | HazeEffect
  | HealEffect
  | HyperBeamEffect
  | JumpKickEffect
  | LeechSeedEffect
  | LightScreenEffect
  | MetronomeEffect
  | MimicEffect
  | MirrorMoveEffect
  | MistEffect
  | NoAdditionalEffect
  | OhkoEffect
  | ParalyzeEffect
  | ParalyzeSideEffect1
  | ParalyzeSideEffect2
  | PayDayEffect
  | PoisonEffect
  | PoisonSideEffect1
  | PoisonSideEffect2
  | RageEffect
  | RecoilEffect
  | ReflectEffect
  | SleepEffect
  | SpecialDamageEffect
  | SpecialDownSideEffect
  | SpecialUp1Effect
  | SpecialUp2Effect
  | SpeedDown1Effect
  | SpeedDownSideEffect
  | SpeedUp2Effect
  | SplashEffect
  | SubstituteEffect
  | SuperFangEffect
  | SwiftEffect
  | SwitchAndTeleportEffect
  | ThrashPetalDanceEffect
  | TransformEffect
  | TrappingEffect
  | TwineedleEffect
  | TwoToFiveAttacksEffect
  deriving (Eq, Enum, Show)
